// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.KevinWithDOB.commands;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc620.KevinWithDOB.Robot;
import org.usfirst.frc620.KevinWithDOB.RobotMap;

/**
 *
 */
public class DriveWithJoystick extends Command {
	public Joystick stick;
	private boolean leftBumper, rightBumper;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveWithJoystick() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	stick = Robot.oi.joystick;
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if(!rightBumper && stick.getRawButton(7) && Robot.driveTrain.getSpeedlvl() !=-1) { // Speed Down bumper
    		Robot.driveTrain.setSpeedlvl(Robot.driveTrain.getSpeedlvl() -1);
        		
    	}else if(!leftBumper && stick.getRawButton(8) && Robot.driveTrain.getSpeedlvl() !=1) { // Speed up bumper
    		Robot.driveTrain.setSpeedlvl(Robot.driveTrain.getSpeedlvl() +1);
    	}
    	
    	rightBumper = stick.getRawButton(7);
    	leftBumper = stick.getRawButton(8);
    	
    	Robot.driveTrain.arcadeDrive(stick.getRawAxis(1),stick.getRawAxis(0)); // drive
//    	RobotMap.driveTrainRobotDrive.arcadeDrive(stick.getRawAxis(1),stick.getRawAxis(0));
//		System.out.println("Run");
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
