// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.KevinWithDOB.commands;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc620.KevinWithDOB.Robot;
import org.usfirst.frc620.KevinWithDOB.RobotMap;

/**
 *
 */
public class ForkLiftComand extends Command {

	boolean leftTrigger = false;
	boolean rightTrigger = false;
	
	Joystick stick = Robot.oi.joystick;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public ForkLiftComand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.forklift);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	if(!leftTrigger && stick.getRawAxis(3) > 0.7) { //if the left trigger was just pressed
    		RobotMap.forkliftTopSolenoid.set(DoubleSolenoid.Value.kForward);
		}
    	
    	if(leftTrigger && !(stick.getRawAxis(3) > 0.7)) { //if the left trigger was just released
    		RobotMap.forkliftTopSolenoid.set(DoubleSolenoid.Value.kReverse);
    	}
    	
		if(!rightTrigger && stick.getRawAxis(2) > 0.7) { //if the right trigger was just pressed
    		RobotMap.forkliftBottomSolenoid.set(DoubleSolenoid.Value.kForward);
		}
		
		if(rightTrigger && !(stick.getRawAxis(2) > 0.7)) { //if the right trigger was just released
			RobotMap.forkliftBottomSolenoid.set(DoubleSolenoid.Value.kReverse);
    	}
		
		leftTrigger = stick.getRawAxis(3) > 0.7;
		rightTrigger = stick.getRawAxis(2) > 0.7;
		
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
